### PR TITLE
Suggested spring clean-up of Code

### PR DESCRIPTION
**Pull request by JesHansen**
I saw your video about this project on reddit and had to take a look at it. I really like it, I think it's a really cool idea!

I've gone over the code base with some light refactorings making it a bit terser. I've tried to leave all functionality as-is, and did not attempt to change any of the architecture.

I've made the changes in (very) small increments, so if you want to grab only a subset of them, you should be able to take whatever part you like.

Thanks for sharing your project! :-)

### CODE REVIEW

**Review by makeratplay — APPROVED** [review]
Yep, should have cleaned these up before I committed.

**Review by makeratplay — APPROVED** [review]
I am still old school with my use of String.Format(), but I like and should use string interpolation more.

**Review by makeratplay — APPROVED** [review]
This all looks goods

**Review by makeratplay — APPROVED** [review]
Agree this is good practice.

**Review by makeratplay — COMMENTED** [review]
Yes, I don't use these fields, but still left them because I excepted others might use them for something.  If this was production code that I expected to maintain for the next 10 years, I would remove them, but since this is hobby code used to teach, I think I would leave them for others to use.

**Review by makeratplay — COMMENTED** [review]
I too like the use of expressions, but not sure if they make this code easier or harder for someone to learn from.  My goal with this code was not write it as efficiently as possible, but to make it easy to understand when I explained it in the video.

**Review by makeratplay — COMMENTED** [review]
Now this is a tough one for me as my coding style is that I like to explicitly define my data types, but I don't always as I will use var at times if the explicit type is a really long string.  Taking the point of view that this code is to teach, I think people should learn explicit  types and then after they know them then start using var sparingly.

**Review by makeratplay — COMMENTED** [review]
Yes it is a unused method, but again thought others might use it in the future. But I do see the point that I didn't build the IPHeader class out fully so where is the line of what to keep and what to remove.

**Review by makeratplay — COMMENTED** [review]
I like the use of .Any() instead of length and should use it more.  
The use of the FirstOrDefault Linq Method does make for cleaner code, but not sure it is easy for a new developer to understand and step through with the debugger. 
Call me old school, but I hate having more than one return in a method and omitting cury braces on one line if statements. 😎

**Review by makeratplay — COMMENTED** [review]
I do like how this reduces the amount of code.

**Review by makeratplay — COMMENTED** [review]
This does reduce the code nicely

**Comment by JesHansen** [comment]
I've dialed back a bit on the amount of changes done, and rebased. Highlights are:

* Restore the unused fields and method in the IPHeader class
* Less LINQ (No more FirstOrDefault)
* No use of 'var' by default
* No multiple function returns in isOutsideUDPTaffice

I think this strikes a nice balance of trying to be modern, pragmatic C# that is useful for teaching, by not being too 'clever' or use code patterns what you wouldn't see in 'real' production code bases.
I'm letting go of this task from here on, so it's now yours to treasure forever. ;-)

**Review by makeratplay — APPROVED** [review]
Looks good. Appreciate you taking the time to contribute to the code and make it better.

**Pull request merged**
